apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-template
  title: Notification Template
  description: send a notification
spec:
  owner: karthikjeeyar
  type: service

 

  # here's the steps that are executed in series in the scaffolder backend
  steps:
  - id: notify
    name: Notify
    action: notification:send
    input:
      recipients: entity
      entityRefs:
        - user:default/guest
      title: 'Template executed'
      info: 'Your template has been executed'
      severity: 'normal'
