apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: notify-template
  title: Notification Template
  description: send a notification
spec:
  owner: karthikjeeyar
  type: service
  steps:
  - id: notify
    name: Notify
    action: notification:send
    input:
      recipients: entity
      entityRefs:
        - user:development/guest
      title: 'Template executed'
      info: 'Your template has been executed'
      severity: 'normal'
