apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vanilla
  title: Vanilla🍦
  description: Use this template if you need to create a new service with just bare bone minimum.
  tags:
    - skeleton
